# Generated by Django 5.1.6 on 2025-03-06 06:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages_images/', verbose_name='Imagen')),
                ('created_at', models.DateField(verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['-created_at'],
            },
        ),
    ]
